### ISSUE TITLE
Impossible to execute INSERT query with json data

### ISSUE THREAD

**Issue by lizdeika** [rinsed-org/rb-snowflake-client#31]
Say we have `tbl` table with a `data` VARIANT column

```ruby
json_string = '{"valid": "json"}'
query = "insert into tbl(data) select parse_json('#{json_string}')"
client.query(query)
```

This will lead to an error something like this:
```
SQL compilation error:\nInvalid expression [PARSE_JSON('{\"valid\":{\"json\"}')] in VALUES clause
```

Because of some type of escapement and added slashes to the query

**Comment by reidnimz** [comment]
@lizdeika appreciate the contribution. It's now available in version 1.1.0
